# Generated by Django 5.1.6 on 2025-02-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='albums',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.musician'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
